"""empty message

Revision ID: bff532be4990
Revises: ee7863d132ba
Create Date: 2021-05-03 20:55:02.003525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff532be4990'
down_revision = 'ee7863d132ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('cancha_nombre', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'cancha_nombre')
    # ### end Alembic commands ###
